"""empty message

Revision ID: 317ea181f7a2
Revises: None
Create Date: 2015-02-06 21:48:14.943092

"""

# revision identifiers, used by Alembic.
revision = '317ea181f7a2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=60), nullable=True),
    sa.Column('lastName', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='general')
    ### end Alembic commands ###
