"""empty message

Revision ID: 8d763d727ed
Revises: None
Create Date: 2015-02-07 16:27:06.965720

"""

# revision identifiers, used by Alembic.
revision = '8d763d727ed'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=60), nullable=True),
    sa.Column('lastName', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='general')
    ### end Alembic commands ###
