"""empty message

Revision ID: 8fc67373be
Revises: None
Create Date: 2015-09-10 18:00:41.252926

"""

# revision identifiers, used by Alembic.
revision = '8fc67373be'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('parent_page', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('access_restricted', sa.Boolean(), nullable=False),
    sa.Column('url_identifier', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_page'], ['content.page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_page', 'url_identifier'),
    schema='content'
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=60), nullable=True),
    sa.Column('lastName', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='general'
    )
    op.create_table('revue_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=60), nullable=True),
    sa.Column('lastName', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='general'
    )
    op.create_table('content_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('text', 'container', 'vuedle', 'announcement', name='content_element_types'), nullable=False),
    sa.Column('sticky', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['general.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_table('menu_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['page'], ['content.page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_table('group_participation',
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['general.group.id'], ),
    sa.ForeignKeyConstraint(['user'], ['general.user.id'], ),
    sa.PrimaryKeyConstraint('group', 'user'),
    schema='general'
    )
    op.create_table('user_permission',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['general.permission.id'], ),
    sa.ForeignKeyConstraint(['user'], ['general.user.id'], ),
    sa.PrimaryKeyConstraint('user', 'permission'),
    schema='general'
    )
    op.create_table('year_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_year_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['general.group.id'], ),
    sa.ForeignKeyConstraint(['parent_year_group'], ['general.year_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='general'
    )
    op.create_table('group_menu',
    sa.Column('menu_entry', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['general.group.id'], ),
    sa.ForeignKeyConstraint(['menu_entry'], ['content.menu_entry.id'], ),
    sa.PrimaryKeyConstraint('group'),
    schema='content'
    )
    op.create_table('menu_entry_relationship',
    sa.Column('child', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child'], ['content.menu_entry.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['content.menu_entry.id'], ),
    sa.PrimaryKeyConstraint('parent', 'child'),
    schema='content'
    )
    op.create_table('page_access_restriction',
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('year_group', sa.Integer(), nullable=False),
    sa.Column('revue_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page'], ['content.page.id'], ),
    sa.ForeignKeyConstraint(['revue_year'], ['general.revue_year.id'], ),
    sa.ForeignKeyConstraint(['year_group'], ['general.year_group.id'], ),
    sa.PrimaryKeyConstraint('page', 'year_group', 'revue_year'),
    schema='content'
    )
    op.create_table('page_content_element',
    sa.Column('content_element', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_element'], ['content.content_element.id'], ),
    sa.ForeignKeyConstraint(['page'], ['content.page.id'], ),
    sa.PrimaryKeyConstraint('content_element', 'page'),
    schema='content'
    )
    op.create_table('text_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['content.content_element.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_table('year_group_participation',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('year_group', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['general.user.id'], ),
    sa.ForeignKeyConstraint(['year'], ['general.revue_year.id'], ),
    sa.ForeignKeyConstraint(['year_group'], ['general.year_group.id'], ),
    sa.PrimaryKeyConstraint('year', 'year_group', 'user'),
    schema='general'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('year_group_participation', schema='general')
    op.drop_table('text_element', schema='content')
    op.drop_table('page_content_element', schema='content')
    op.drop_table('page_access_restriction', schema='content')
    op.drop_table('menu_entry_relationship', schema='content')
    op.drop_table('group_menu', schema='content')
    op.drop_table('year_group', schema='general')
    op.drop_table('user_permission', schema='general')
    op.drop_table('group_participation', schema='general')
    op.drop_table('menu_entry', schema='content')
    op.drop_table('content_element', schema='content')
    op.drop_table('user', schema='general')
    op.drop_table('revue_year', schema='general')
    op.drop_table('registration', schema='general')
    op.drop_table('permission', schema='general')
    op.drop_table('group', schema='general')
    op.drop_table('page', schema='content')
    ### end Alembic commands ###
